import React, { useMemo, useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from '@/components/ui/button';
import { useEnrollment } from '@/hooks/enrollments';
import { useClientById } from '@/hooks/clients';
import { useQuery } from '@tanstack/react-query';
import { coursesService } from '@/services/coursesService';
import { currencyRemoveMaskToNumber } from '@/lib/masks/currency';
import BudgetPreview from '@/components/school/BudgetPreview';
import InstallmentPreviewCard from '@/components/school/InstallmentPreviewCard';
import SignatureLinkCard from '@/components/school/SignatureLinkCard';
import ResponsibleInfoCard from '@/components/school/ResponsibleInfoCard';
import ProposalAttendanceCard from '@/components/school/ProposalAttendanceCard';
import ProposalContractsTab from './ProposalContractsTab';
import ProposalLogsTab from './ProposalLogsTab';
import { useLocation, useNavigate } from 'react-router-dom';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { toast } from 'sonner';
import { CheckCircle, Clock, User, Mail, Phone, BookOpen, Layers, Calendar, Hash, CircleDollarSign, Info, Loader2, Copy, MessageCircle } from 'lucide-react';

interface ProposalViewContentProps {
  /**
   * id
   * pt-BR: ID da matrícula/proposta para carregar dados.
   * en-US: Enrollment/Proposal ID to load data.
   */
  id: string;
}
/**
 * StatCard
 * pt-BR: Card de métrica para uso interno na visualização de proposta.
 * en-US: Metric card for internal use in proposal view.
 */
function StatCard({ label, value, icon: Icon, colorClass = "text-primary", bgClass = "bg-primary/10" }: any) {
  return (
    <Card className="border-none shadow-sm bg-zinc-50/50 dark:bg-zinc-900/50 backdrop-blur-sm overflow-hidden transition-all hover:shadow-md hover:bg-white dark:hover:bg-zinc-900 border border-border/40">
      <CardContent className="p-5 flex items-center gap-4">
        <div className={`p-3 rounded-2xl ${bgClass} ${colorClass}`}>
          <Icon className="h-5 w-5" />
        </div>
        <div className="flex flex-col gap-0.5">
          <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/70">{label}</span>
          <span className="text-lg font-bold tracking-tight text-foreground">{value}</span>
        </div>
      </CardContent>
    </Card>
  );
}

/**
 * ProposalViewContent
 * pt-BR: Componente de visualização de proposta somente leitura, com abas para Visão Geral e Contratos.
 * en-US: Read-only proposal view component, with tabs for Overview and Contracts.
 */
export default function ProposalViewContent({ id }: ProposalViewContentProps) {
  /**
   * handleCopyAdministrationText
   * pt-BR: Copia o texto administrativo gerado pelo backend para a area de transferencia.
   * en-US: Copies the admin text generated by the backend to the clipboard.
   */
  async function handleCopyAdministrationText(text: string) {
    try {
      await navigator.clipboard.writeText(text);
      toast.success('Texto de administração copiado.');
    } catch {
      toast.error('Não foi possível copiar o texto de administração.');
    }
  }

  /**
   * openAdministrationTextInWhatsAppWeb
   * pt-BR: Abre o WhatsApp Web com o texto administrativo preenchido para envio.
   *        O usuário escolhe a conversa após abrir a interface do WhatsApp Web.
   * en-US: Opens WhatsApp Web with the administrative text prefilled for sending.
   *      The user chooses the conversation after WhatsApp Web opens.
   */
  function openAdministrationTextInWhatsAppWeb(text: string) {
    if (!text.trim()) {
      toast.error('O texto de administração está vazio.');
      return;
    }

    const url = `https://web.whatsapp.com/send?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  }

  /**
   * normalizeSignatureStatus
   * pt-BR: Normaliza o status de assinatura vindo do backend para comparações consistentes.
   * en-US: Normalizes the signature status from backend for consistent comparisons.
   */
  function normalizeSignatureStatus(rawStatus: unknown): string {
    return String(rawStatus ?? '')
      .trim()
      .toLowerCase()
      .replace(/\s+/g, '_');
  }

  /**
   * formatSignatureStatusLabel
   * pt-BR: Converte o valor técnico do backend em um rótulo amigável para o badge.
   * en-US: Converts backend status into a user-friendly badge label.
   */
  function formatSignatureStatusLabel(normalizedStatus: string): string {
    const labelsByStatus: Record<string, string> = {
      aprovado: 'Aprovada',
      assinado: 'Assinada',
      em_andamento: 'Em Andamento',
      aguardando_assinatura: 'Aguardando Assinatura',
      pendente: 'Pendente',
      recusado: 'Recusada',
      reprovado: 'Reprovada',
      cancelado: 'Cancelada',
      expirado: 'Expirada',
    };

    if (labelsByStatus[normalizedStatus]) return labelsByStatus[normalizedStatus];

    return normalizedStatus
      .split('_')
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(' ');
  }

  const { data: enrollment } = useEnrollment(String(id || ''));
  const location = useLocation();
  const navigate = useNavigate();

  const infoResponsavel = (enrollment as any)?.responsavel;
  const rawZapsignResp = (enrollment as any)?.meta?.processo_assinatura_responsavel;
  const zapsignDataResp = useMemo(() => {
    if (!rawZapsignResp) return null;
    try {
      return typeof rawZapsignResp === 'string' ? JSON.parse(rawZapsignResp) : rawZapsignResp;
    } catch {
      return null;
    }
  }, [rawZapsignResp]);
  const signatureLinkResp = zapsignDataResp?.signers?.[0]?.sign_url || zapsignDataResp?.signers?.[0]?.signing_link || '';

  /**
   * getInitialTab
   * pt-BR: Obtém a aba inicial da URL: hash (#overview | #admin | #contracts) ou query (?tab=...).
   * en-US: Gets initial tab from URL: hash (#overview | #admin | #contracts) or query (?tab=...).
   */
  const getInitialTab = useMemo(() => {
    const hash = String(location.hash || '').replace('#', '');
    if (hash === 'overview' || hash === 'admin' || hash === 'contracts' || hash === 'logs') return hash;
    const qs = new URLSearchParams(location.search || '');
    const t = qs.get('tab');
    if (t === 'overview' || t === 'admin' || t === 'contracts' || t === 'logs') return t;
    return 'overview';
  }, [location.hash, location.search]);

  /**
   * tab
   * pt-BR: Estado controlado da aba atual, sincronizado com a URL.
   * en-US: Controlled state of the current tab, synchronized with the URL.
   */
  const [tab, setTab] = useState<string>(getInitialTab);

  /**
   * syncTabFromUrl
   * pt-BR: Atualiza o estado quando o hash/query muda externamente.
   * en-US: Updates state when hash/query changes externally.
   */
  useEffect(() => {
    setTab(getInitialTab);
  }, [getInitialTab]);

  /**
   * handleTabChange
   * pt-BR: Atualiza aba e escreve o hash na URL (#overview | #admin | #contracts).
   * en-US: Updates tab and writes hash in the URL (#overview | #admin | #contracts).
   */
  function handleTabChange(next: string) {
    setTab(next);
    navigate(
      { pathname: location.pathname, search: location.search, hash: `#${next}` },
      { replace: true }
    );
  }

  const clientId = useMemo(() => {
    const v = (enrollment as any)?.id_cliente ?? (enrollment as any)?.client_id;
    return v ? String(v) : '';
  }, [enrollment]);
  const { data: client } = useClientById(clientId, { enabled: !!clientId });

  const courseId = useMemo(() => {
    const v = (enrollment as any)?.id_curso ?? (enrollment as any)?.course_id;
    return v ? Number(v) : undefined;
  }, [enrollment]);
  const { data: course } = useQuery({
    queryKey: ['courses', 'byId', courseId],
    queryFn: async () => (courseId ? coursesService.getById(courseId) : null),
    enabled: !!courseId,
    staleTime: 5 * 60 * 1000,
  });

  /**
   * computeValidityDate
   * pt-BR: Soma N dias à data atual e formata dd/MM/yyyy.
   * en-US: Adds N days to today and formats dd/MM/yyyy.
   */
  function computeValidityDate(daysStr?: string, baseDate?: string): string {
    const days = parseInt(String(daysStr ?? ''), 10);
    if (!Number.isFinite(days) || days <= 0) return '';
    const d = baseDate ? new Date(baseDate) : new Date();
    d.setDate(d.getDate() + days);
    const dd = String(d.getDate()).padStart(2, '0');
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const yyyy = d.getFullYear();
    return `${dd}/${mm}/${yyyy}`;
  }

  /**
   * formatCurrencyBRL
   * pt-BR: Formata número em BRL (R$).
   * en-US: Formats number into BRL (R$).
   */
  function formatCurrencyBRL(value: number): string {
    try {
      return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value) || 0);
    } catch {
      return `R$ ${(Number(value) || 0).toFixed(2)}`;
    }
  }

  /**
   * maskMonetaryDisplay
   * pt-BR: Aplica máscara monetária para exibição; retorna vazio se não houver valor.
   * en-US: Applies monetary mask for display; returns empty when no value.
   */
  function maskMonetaryDisplay(raw: string | number | undefined | null): string {
    const s = String(raw ?? '').trim();
    if (!s || s === 'null') return '';
    // pt-BR: Se já tiver vírgula ou símbolo, remove máscara; caso contrário, é número puro do back
    // en-US: If it has comma or symbol, unmask; otherwise it is a pure number from backend
    const num = (s.includes(',') || s.includes('R$')) ? currencyRemoveMaskToNumber(s) : (Number(s) || 0);
    return formatCurrencyBRL(num);
  }

  /**
   * computeModulo
   * pt-BR: Retorna módulo correto baseado no tipo de curso.
   * en-US: Returns proper module based on course type.
   */
  function computeModulo(enr: any, cursoTipo: string) {
    try {
      if (String(cursoTipo) === '4') {
        return enr?.orc?.modulos?.[0] ?? '';
      }
      return enr?.orc?.modulo ?? '';
    } catch {
      return '';
    }
  }

  const subtotalMasked = useMemo(() => maskMonetaryDisplay((enrollment as any)?.subtotal), [enrollment]);
  const totalMasked = useMemo(() => maskMonetaryDisplay((enrollment as any)?.total), [enrollment]);
  const descontoMasked = useMemo(() => maskMonetaryDisplay((enrollment as any)?.desconto), [enrollment]);
  const inscricaoMasked = useMemo(() => maskMonetaryDisplay((enrollment as any)?.inscricao), [enrollment]);
  const validadeDias = useMemo(() => String((enrollment as any)?.meta?.validade || (enrollment as any)?.validade || '14'), [enrollment]);
  const emissionDate = useMemo(() => (enrollment as any)?.data || (enrollment as any)?.created_at, [enrollment]);
  const clientName = client?.name || (client as any)?.nome || (enrollment as any)?.cliente_nome || (enrollment as any)?.cliente?.name || '';
  const clientPhone = client?.config?.celular || client?.config?.telefone_residencial || (enrollment as any)?.cliente?.celular || (enrollment as any)?.cliente?.config?.celular || '';
  const clientEmail = client?.email || (enrollment as any)?.cliente?.email || '';
  const proposalStatus = String((enrollment as any)?.status || 'a').toLowerCase();
  const curso_tipo = String((enrollment as any)?.curso_tipo || '');
  const administrationText = useMemo(
    () => String((enrollment as any)?.administration_text || '').trim(),
    [enrollment]
  );
  const showAdministrationTextCard = administrationText.length > 0;
  const canSendAdministrationTextByWhatsApp = showAdministrationTextCard && proposalStatus === 'g';
  const modulo = computeModulo(enrollment as any, curso_tipo);
  const modulesList = useMemo(() => {
    const list = (enrollment as any)?.orc?.modulos;
    return Array.isArray(list) ? list : undefined;
  }, [enrollment]);

  const etapa1Discount = useMemo(() => {
    try {
        const orc = (enrollment as any)?.orc;
        return Number(orc?.meta?.etapa1_desconto || 0);
    } catch {
        return 0;
    }
  }, [enrollment]);

  const fuelExternalText = (enrollment as any)?.meta?.texto_combustivel || '';

  const linkAssinatura = useMemo(() => {
    let signUrl = (enrollment as any)?.link_assinatura || '';
    if (!signUrl) {
      const clientId = (enrollment as any)?.id_cliente || (enrollment as any)?.client_id;
      const id = (enrollment as any)?.id;
      if (clientId && id) {
        signUrl = `${window.location.origin}/aluno/assinatura/${clientId}_${id}/1`;
      }
    }
    return signUrl;
  }, [enrollment]);

  const parcelamento = useMemo(() => {
    return ((enrollment as any)?.orc?.parcelamento ?? null) as any;
  }, [enrollment]);

  const meta = (enrollment as any)?.meta || {};
  const statusAssinatura = useMemo(
    () => normalizeSignatureStatus(meta?.status_assinatura),
    [meta?.status_assinatura]
  );

  // ZapSign Status Check
  const rawZapsign = meta?.processo_assinatura;
  const zapsignBase = typeof rawZapsign === 'string' ? (JSON.parse(rawZapsign) || {}) : (rawZapsign || {});
  const zapsignData = zapsignBase?.enviar?.response || zapsignBase;
  const hasZapsign = zapsignData && typeof zapsignData === 'object' && (zapsignData.token || zapsignData.signers);
  
  // pt-BR: Só considera assinado via ZapSign se o status for explicitamente 'signed' ou 'completed'
  const isZapsignSigned = hasZapsign && (zapsignData.status === 'signed' || zapsignData.status === 'completed');
  
  const hasLinksAssinados = Boolean(meta?.salvar_links_assinados) || Object.keys(meta || {}).some((k) => k.startsWith('salvar_links_assinados_'));
  const contratoAceito = String((enrollment as any)?.contrato?.aceito_contrato || '').toLowerCase() === 'on';
  
  // pt-BR: Se tem ZapSign, a palavra final é do status do ZapSign. Se não tem, olha para o manual/local.
  const isAssinado = hasZapsign ? isZapsignSigned : (hasLinksAssinados || contratoAceito);
  
  const isZapsignPending = hasZapsign && !isZapsignSigned;

  const status = isAssinado
    ? 'assinado'
    : (isZapsignPending ? 'em_andamento' : (statusAssinatura || 'em_andamento'));
  
  const statusMessage = (() => {
    if (isAssinado) return 'Está proposta ja está aprovada e assinada.';
    if (isZapsignPending) return 'Assinatura digital em andamento (ZapSign).';
    if (status === 'aprovado') return 'A proposta foi aprovada e está aguardando assinatura digital.';
    if (status === 'recusado' || status === 'reprovado') return 'A proposta foi recusada e requer revisão antes de seguir.';
    if (status === 'cancelado') return 'A proposta foi cancelada.';
    if (status === 'expirado') return 'A proposta expirou e precisa ser revalidada.';
    return '';
  })();
  
  const badgeLabel = isAssinado
    ? 'Assinada'
    : (isZapsignPending ? 'Aprovação em Andamento' : formatSignatureStatusLabel(status));

  const badgeColor = isAssinado
    ? 'bg-green-600'
    : (isZapsignPending
        ? 'bg-amber-500'
        : ((status === 'aprovado' && 'bg-blue-600')
            || ((status === 'recusado' || status === 'reprovado') && 'bg-red-600')
            || (status === 'cancelado' && 'bg-zinc-600')
            || (status === 'expirado' && 'bg-orange-600')
            || (status === 'pendente' && 'bg-amber-500')
            || (status === 'aguardando_assinatura' && 'bg-indigo-600')
            || 'bg-slate-600'));

  return (
    <div className="space-y-6">
      <Tabs value={tab} onValueChange={handleTabChange} className="w-full">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
           <TabsList className="grid grid-cols-4 w-full md:w-[540px] bg-muted/50 p-1 rounded-xl print:hidden">
              <TabsTrigger value="overview" asChild className="rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm transition-all"><a href="#overview">Geral</a></TabsTrigger>
              <TabsTrigger value="admin" asChild className="rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm transition-all"><a href="#admin">Administração</a></TabsTrigger>
              <TabsTrigger value="contracts" asChild className="rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm transition-all"><a href="#contracts">Contratos</a></TabsTrigger>
              <TabsTrigger value="logs" asChild className="rounded-lg data-[state=active]:bg-background data-[state=active]:shadow-sm transition-all"><a href="#logs">Auditoria</a></TabsTrigger>
           </TabsList>
           
           <div className="flex items-center gap-2 print:hidden">
              <Badge className={`${badgeColor} text-white border-none py-1.5 px-4 rounded-full text-[10px] font-bold uppercase tracking-widest shadow-sm`}>
                <span className="inline-flex items-center gap-2">
                  {isAssinado ? <CheckCircle className="h-3.5 w-3.5" /> : <Clock className="h-3.5 w-3.5" />}
                  {badgeLabel}
                </span>
              </Badge>
           </div>
        </div>

        <TabsContent value="overview" className="space-y-8 mt-0 print:mt-0 animate-in fade-in slide-in-from-bottom-2 duration-500">
            {/* KPI Section */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 print:hidden">
              <StatCard label="Total da Proposta" value={totalMasked || 'R$ 0,00'} icon={CircleDollarSign} colorClass="text-green-600" bgClass="bg-green-50" />
              <StatCard label="ID da Matrícula" value={`#${id}`} icon={Hash} colorClass="text-zinc-600" bgClass="bg-zinc-100" />
              <StatCard label="Validade" value={computeValidityDate(validadeDias, emissionDate) || 'Expirada'} icon={Calendar} colorClass="text-blue-600" bgClass="bg-blue-50" />
              <StatCard label="Consultor" value={(enrollment as any)?.consultor?.name || (enrollment as any)?.autor_name || 'Sistema'} icon={User} colorClass="text-purple-600" bgClass="bg-purple-50" />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
               {/* Main Content (Left) */}
               <div className="lg:col-span-8 space-y-8">
                  {statusMessage && (
                      <Alert className={`border-none shadow-sm print:hidden ${isAssinado ? 'bg-green-50/50 text-green-800' : (isZapsignPending ? 'bg-amber-50/50 text-amber-800' : ((status === 'aprovado' && 'bg-blue-50/50 text-blue-800') || ((status === 'recusado' || status === 'reprovado') && 'bg-red-50/50 text-red-800') || (status === 'cancelado' && 'bg-zinc-50/50 text-zinc-800') || (status === 'expirado' && 'bg-orange-50/50 text-orange-800') || 'bg-slate-50/50 text-slate-800'))} rounded-2xl p-4 flex items-start gap-4`}>
                      <div className={`p-2 rounded-xl scale-110 ${isAssinado ? 'bg-green-100' : (isZapsignPending ? 'bg-amber-100' : ((status === 'aprovado' && 'bg-blue-100') || ((status === 'recusado' || status === 'reprovado') && 'bg-red-100') || (status === 'cancelado' && 'bg-zinc-100') || (status === 'expirado' && 'bg-orange-100') || 'bg-slate-100'))}`}>
                        {(isAssinado || status === 'aprovado') ? <CheckCircle className="h-5 w-5" /> : ((status === 'recusado' || status === 'reprovado' || status === 'cancelado' || status === 'expirado') ? <Info className="h-5 w-5" /> : <Clock className="h-5 w-5" />)}
                      </div>
                      <div className="flex flex-col gap-0.5">
                        <AlertTitle className="text-xs font-bold uppercase tracking-widest opacity-70">Status Atual</AlertTitle>
                        <AlertDescription className="text-sm font-medium">{statusMessage}</AlertDescription>
                      </div>
                    </Alert>
                  )}

                  {/* Detalhes da Proposta Comercial */}
                  <BudgetPreview
                      title="Proposta Comercial"
                      clientName={clientName}
                      clientId={client?.id ? String(client.id) : undefined}
                      clientPhone={clientPhone}
                      clientEmail={clientEmail}
                      course={course as any}
                      courseName={(course as any)?.titulo || (course as any)?.nome || (enrollment as any)?.course_name || (enrollment as any)?.curso_nome}
                      turmaName={(enrollment as any)?.turma_name || (enrollment as any)?.turma_nome}
                      module={modulo}
                      modules={modulesList}
                      discountLabel="Desconto"
                      discountAmountMasked={descontoMasked}
                      subtotalMasked={subtotalMasked}
                      totalMasked={totalMasked}
                      validityDate={computeValidityDate(validadeDias, emissionDate)}
                      validityDays={validadeDias}
                      inscricaoMasked={inscricaoMasked}
                      etapa1Discount={etapa1Discount}
                      fuelExternalText={fuelExternalText}
                      parcelamento={parcelamento}
                      emissionDate={emissionDate}
                  />

               </div>

               {/* Sidebar (Right) */}
               <div className="lg:col-span-4 space-y-6 print:hidden">
                  <ProposalAttendanceCard
                    enrollmentId={String(id)}
                    clientId={clientId || undefined}
                    clientName={clientName || undefined}
                    status={proposalStatus}
                    meta={meta}
                    proposalAmountLabel={totalMasked || 'R$ 0,00'}
                  />

                  {/* Cards de Assinatura movidos da aba Admin */}
                  {linkAssinatura && <SignatureLinkCard link={linkAssinatura} />}
                  {infoResponsavel && <ResponsibleInfoCard data={infoResponsavel} signatureLink={signatureLinkResp} />}
               </div>
            </div>
        </TabsContent>

        <TabsContent value="admin" className="mt-0 pt-4 animate-in fade-in slide-in-from-right-2 duration-500 outline-none">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            <div className="lg:col-span-8 space-y-8">
              <Card className="border-none shadow-sm rounded-2xl overflow-hidden bg-zinc-50/30">
                <CardHeader className="pb-3 border-b border-border/40">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-center gap-2">
                      <div className="p-1.5 rounded-lg bg-primary/10 text-primary">
                        <Info className="h-4 w-4" />
                      </div>
                      <div className="space-y-1">
                        <CardTitle className="text-xs font-bold uppercase tracking-widest">Texto de Administração</CardTitle>
                        <p className="text-xs text-muted-foreground">
                          Revise, copie ou envie o texto pelo WhatsApp Web quando a matrícula estiver matriculada.
                        </p>
                      </div>
                    </div>
                    <div className="flex flex-col sm:flex-row gap-2">
                      <Button
                        type="button"
                        size="sm"
                        variant="outline"
                        className="h-8 rounded-lg"
                        onClick={() => handleCopyAdministrationText(administrationText)}
                        disabled={!showAdministrationTextCard}
                      >
                        <Copy className="mr-2 h-3.5 w-3.5" />
                        Copiar
                      </Button>
                      <Button
                        type="button"
                        size="sm"
                        className="h-8 rounded-lg"
                        disabled={!canSendAdministrationTextByWhatsApp}
                        onClick={() => openAdministrationTextInWhatsAppWeb(administrationText)}
                      >
                        <MessageCircle className="mr-2 h-3.5 w-3.5" />
                        WhatsApp Web
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="pt-5">
                  {!showAdministrationTextCard ? (
                    <div className="rounded-xl border border-dashed border-border/60 bg-white px-4 py-6 text-sm text-muted-foreground">
                      O texto de administração ainda não está disponível para esta proposta.
                    </div>
                  ) : (
                    <>
                      {!canSendAdministrationTextByWhatsApp && (
                        <div className="mb-3 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700">
                          O envio pelo WhatsApp Web fica disponível quando a proposta estiver matriculada.
                        </div>
                      )}
                      <textarea
                        readOnly
                        value={administrationText}
                        className="min-h-[420px] w-full rounded-xl border border-border/50 bg-white px-3 py-3 text-xs leading-5 text-foreground shadow-sm outline-none resize-y"
                      />
                    </>
                  )}
                </CardContent>
              </Card>
            </div>

            <div className="lg:col-span-4 space-y-6 print:hidden">
              <Card className="border-none shadow-sm rounded-2xl overflow-hidden bg-zinc-50/30">
                <CardHeader className="pb-3 border-b border-border/40">
                  <div className="flex items-center gap-2">
                    <div className="p-1.5 rounded-lg bg-primary/10 text-primary">
                      <Info className="h-4 w-4" />
                    </div>
                    <CardTitle className="text-xs font-bold uppercase tracking-widest">Resumo Operacional</CardTitle>
                  </div>
                </CardHeader>
                <CardContent className="pt-5 space-y-6">
                  <div className="space-y-4">
                    <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/60 px-1">Identificação</span>
                    <div className="space-y-3">
                      <div className="flex items-center gap-3 p-3 rounded-xl bg-white dark:bg-zinc-900 border border-border/40 shadow-sm">
                        <div className="p-2 rounded-lg bg-zinc-100 text-zinc-500"><User className="h-4 w-4" /></div>
                        <div className="flex flex-col min-w-0">
                          <span className="text-[10px] font-bold opacity-50 uppercase leading-none mb-0.5">Cliente</span>
                          <span className="text-sm font-bold leading-tight truncate">{clientName || '—'}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 p-3 rounded-xl bg-white dark:bg-zinc-900 border border-border/40 shadow-sm">
                        <div className="p-2 rounded-lg bg-zinc-100 text-zinc-500"><Mail className="h-4 w-4" /></div>
                        <div className="flex flex-col min-w-0">
                          <span className="text-[10px] font-bold opacity-50 uppercase leading-none mb-0.5">E-mail</span>
                          <span className="text-sm font-bold leading-tight truncate">{clientEmail || '—'}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 p-3 rounded-xl bg-white dark:bg-zinc-900 border border-border/40 shadow-sm">
                        <div className="p-2 rounded-lg bg-zinc-100 text-zinc-500"><Phone className="h-4 w-4" /></div>
                        <div className="flex flex-col min-w-0">
                          <span className="text-[10px] font-bold opacity-50 uppercase leading-none mb-0.5">WhatsApp</span>
                          <span className="text-sm font-bold leading-tight truncate">{clientPhone || '—'}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/60 px-1">Acadêmico</span>
                    <div className="space-y-3">
                      <div className="flex items-center gap-3 p-3 rounded-xl bg-white dark:bg-zinc-900 border border-border/40 shadow-sm">
                        <div className="p-2 rounded-lg bg-primary/10 text-primary"><BookOpen className="h-4 w-4" /></div>
                        <div className="flex flex-col min-w-0">
                          <span className="text-[10px] font-bold opacity-50 uppercase leading-none mb-0.5">Curso</span>
                          <span className="text-sm font-bold leading-tight truncate">{(course as any)?.titulo || (course as any)?.nome || '—'}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 p-3 rounded-xl bg-white dark:bg-zinc-900 border border-border/40 shadow-sm">
                        <div className="p-2 rounded-lg bg-primary/10 text-primary"><Layers className="h-4 w-4" /></div>
                        <div className="flex flex-col min-w-0">
                          <span className="text-[10px] font-bold opacity-50 uppercase leading-none mb-0.5">Turma</span>
                          <span className="text-sm font-bold leading-tight truncate">{(enrollment as any)?.turma_name || (enrollment as any)?.turma_nome || '—'}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </TabsContent>

        <TabsContent value="contracts" className="mt-0 pt-4 animate-in fade-in slide-in-from-right-2 duration-500 outline-none">
             {tab === 'contracts' && clientId && id ? (
                <ProposalContractsTab 
                  clientId={clientId} 
                  enrollmentId={id} 
                  meta={meta} 
                  courseName={(course as any)?.titulo || (course as any)?.nome || (enrollment as any)?.course_name || (enrollment as any)?.curso_nome}
                  signatureLink={linkAssinatura}
                  onGoToOverview={() => handleTabChange('overview')}
                  responsavel={infoResponsavel}
                />
             ) : (
                <div className="flex flex-col items-center justify-center py-20 text-muted-foreground gap-3">
                    <Loader2 className="h-8 w-8 animate-spin opacity-20" />
                    <span className="text-sm font-medium">Carregando documentos...</span>
                </div>
             )}
        </TabsContent>
        
        <TabsContent value="logs" className="mt-0 pt-4 animate-in fade-in slide-in-from-right-2 duration-500 outline-none">
          {tab === 'logs' && id ? (
            <ProposalLogsTab enrollmentId={id} />
          ) : (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground gap-3">
                <Loader2 className="h-8 w-8 animate-spin opacity-20" />
                <span className="text-sm font-medium">Carregando histórico...</span>
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
