<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            // ── Master (id=1) ──────────────────────────────────────
            [
                'name' => 'Fernando Queta',
                'email' => 'fernando@maisaqui.com.br',
                'password' => Hash::make('fquetapro'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 1,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Usuario demo',
                'email' => 'suporte@maisaqui.com.br',
                'password' => Hash::make('demo'),
                'celular' => '(32)99164-8202',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 1,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Programador',
                'email' => 'quetafernando1@gmail.com',
                'password' => Hash::make('programador'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 1,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Programador sandbox',
                'email' => 'suporte1@maisaqui.com.br',
                'password' => Hash::make('sandbox'),
                'celular' => '(32)99999-9999',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 1,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],

            // ── Administrador (id=2) ────────────────────────────────
            [
                'name' => 'Leandro Lopardi',
                'email' => 'contato@aeroclubejf.com.br',
                'password' => Hash::make('leandro'),
                'celular' => '(32)99148-0920',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => 'id_contatada',
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Monique Ribeiro',
                'email' => 'monique@aeroclubejf.com.br',
                'password' => Hash::make('monique'),
                'celular' => '(21)99572-9494',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => 'id_testemunha1',
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'f',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Maria Luiza da Silva Sanches',
                'email' => 'luiza@aeroclubejf.com.br',
                'password' => Hash::make('luiza'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'f',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Jessica Fabri',
                'email' => 'jessica@aeroclubejf.com.br',
                'password' => Hash::make('jessica'),
                'celular' => '(32)98889-0086',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'f',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Francis Oliveira',
                'email' => 'fran@aeroclubejf.com.br',
                'password' => Hash::make('fran'),
                'celular' => '(32)99845-1557',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Júlia Zanovello Borges',
                'email' => 'julia@aeroclubejf.com.br',
                'password' => Hash::make('julia'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'f',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Gabriella Fernandes',
                'email' => 'gabriela@aeroclubejf.com.br',
                'password' => Hash::make('gabriella'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'f',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Deborah Pacheco',
                'email' => 'deborah@aeroclubejf.com.br',
                'password' => Hash::make('deborah'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 2,
                'tipo_pessoa' => 'pf',
                'genero' => 'f',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Assessoria Matgo',
                'email' => 'diagnostico@assessoriamatgo.com',
                'password' => Hash::make('matgo'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 2,
                'tipo_pessoa' => 'pj',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],

            // ── Auxiliar Adminstrativo (id=3) ───────────────────────
            [
                'name' => 'Renan Coimbra',
                'email' => 'renan@aeroclubejf.com.br',
                'password' => Hash::make('renan'),
                'celular' => '(32)98855-2280',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => 'id_testemunha2',
                'permission_id' => 3,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Rayane Moreira',
                'email' => 'comercial04@aeroclubejf.com.br',
                'password' => Hash::make('rayane'),
                'celular' => '(32)99926-6912',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 3,
                'tipo_pessoa' => 'pf',
                'genero' => 'f',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Pedro Lucas de Sá Cunha',
                'email' => 'pcunhq334@gmail.com',
                'password' => Hash::make('pedro'),
                'celular' => '(32)98442-8672',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 3,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Igor Sell',
                'email' => 'igsellr@gmail.com',
                'password' => Hash::make('igor'),
                'celular' => '(32)98426-2973',
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 3,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
            [
                'name' => 'Lenin Ferreira Francisco',
                'email' => 'lenin@aeroclubejf.com.br',
                'password' => Hash::make('lenin'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 3,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],

            // ── Consultor (id=5) ───────────────────────────────────
            [
                'name' => 'Lazaro Pancoti',
                'email' => 'lazaro@aeroclubejf.com.br',
                'password' => Hash::make('lazaro'),
                'status' => 'actived',
                'verificado' => 'n',
                'token' => uniqid(),
                'permission_id' => 5,
                'tipo_pessoa' => 'pf',
                'genero' => 'm',
                'ativo' => 's',
                'excluido' => 'n',
                'deletado' => 'n',
            ],
        ];

        foreach ($users as $userData) {
            User::updateOrCreate(
                ['email' => $userData['email']],
                $userData
            );
        }
    }
}
